name: Streamlit App Monitor

on:
  schedule:
    - cron: '0 */11 * * *'  # Runs every 11 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run monitor script
      run: python streamlit_app_monitor.py
      env:
        PYTHONUNBUFFERED: 1
    
    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: monitor-log
        path: streamlit_monitor.log
        retention-days: 7 