name: Streamlit App Monitor

on:
  schedule:
    - cron: '0 */11 * * *'  # Runs every 11 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        # Get Chromium version from snap
        CHROME_VERSION=$(snap list chromium | grep chromium | awk '{print $2}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run monitor script
      run: python streamlit_app_monitor.py
      env:
        PYTHONUNBUFFERED: 1
        CHROME_DRIVER_PATH: /usr/local/bin/chromedriver
      continue-on-error: true  # Continue even if some apps fail
    
    - name: Upload log file
      if: always()  # Run this step even if previous steps failed
      uses: actions/upload-artifact@v4
      with:
        name: monitor-log
        path: streamlit_monitor.log
        retention-days: 7 